// import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: "TubeMind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          padding: 0,
          margin: 0,
        }}
      >
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
